//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ChatPt.proto
namespace ChivaVR.Net.Packet
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChatTextPt")]
  public partial class ChatTextPt : global::ProtoBuf.IExtensible
  {
    public ChatTextPt() {}
    
    private string _objectid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"objectid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string objectid
    {
      get { return _objectid; }
      set { _objectid = value; }
    }
    private int _userid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"userid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int userid
    {
      get { return _userid; }
      set { _userid = value; }
    }
    private string _username;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"username", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string username
    {
      get { return _username; }
      set { _username = value; }
    }
    private string _sendId;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"sendId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sendId
    {
      get { return _sendId; }
      set { _sendId = value; }
    }
    private ChivaVR.Net.Packet.SendType _sndType;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"sndType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ChivaVR.Net.Packet.SendType sndType
    {
      get { return _sndType; }
      set { _sndType = value; }
    }
    private string _msg;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string msg
    {
      get { return _msg; }
      set { _msg = value; }
    }
    private string _sendTime = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"sendTime", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sendTime
    {
      get { return _sendTime; }
      set { _sendTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChatTextStatePt")]
  public partial class ChatTextStatePt : global::ProtoBuf.IExtensible
  {
    public ChatTextStatePt() {}
    
    private string _objectid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"objectid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string objectid
    {
      get { return _objectid; }
      set { _objectid = value; }
    }
    private string _state;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string state
    {
      get { return _state; }
      set { _state = value; }
    }
    private int _userid;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"userid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int userid
    {
      get { return _userid; }
      set { _userid = value; }
    }
    private string _username;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"username", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string username
    {
      get { return _username; }
      set { _username = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChatFilePt")]
  public partial class ChatFilePt : global::ProtoBuf.IExtensible
  {
    public ChatFilePt() {}
    
    private string _objectid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"objectid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string objectid
    {
      get { return _objectid; }
      set { _objectid = value; }
    }
    private int _userid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"userid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int userid
    {
      get { return _userid; }
      set { _userid = value; }
    }
    private string _username;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"username", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string username
    {
      get { return _username; }
      set { _username = value; }
    }
    private string _sendId;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"sendId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sendId
    {
      get { return _sendId; }
      set { _sendId = value; }
    }
    private ChivaVR.Net.Packet.SendType _sndType;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"sndType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ChivaVR.Net.Packet.SendType sndType
    {
      get { return _sndType; }
      set { _sndType = value; }
    }
    private string _filename;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"filename", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string filename
    {
      get { return _filename; }
      set { _filename = value; }
    }
    private int _packageSize;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"packageSize", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int packageSize
    {
      get { return _packageSize; }
      set { _packageSize = value; }
    }
    private int _packageCount;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"packageCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int packageCount
    {
      get { return _packageCount; }
      set { _packageCount = value; }
    }
    private int _fileLength;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"fileLength", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fileLength
    {
      get { return _fileLength; }
      set { _fileLength = value; }
    }
    private int _fileIndex;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"fileIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fileIndex
    {
      get { return _fileIndex; }
      set { _fileIndex = value; }
    }
    private byte[] _fileContent;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"fileContent", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] fileContent
    {
      get { return _fileContent; }
      set { _fileContent = value; }
    }
    private string _sendTime = "";
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"sendTime", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sendTime
    {
      get { return _sendTime; }
      set { _sendTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"SendType")]
    public enum SendType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SEND_POINT", Value=1)]
      SEND_POINT = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SEND_GOUP", Value=2)]
      SEND_GOUP = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SEND_MONY", Value=3)]
      SEND_MONY = 3
    }
  
}