//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: CrudPt.proto
namespace ChivaVR.Net.Packet
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"QueryPt")]
  public partial class QueryPt : global::ProtoBuf.IExtensible
  {
    public QueryPt() {}
    
    private string _token;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string token
    {
      get { return _token; }
      set { _token = value; }
    }
    private string _sql;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"sql", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sql
    {
      get { return _sql; }
      set { _sql = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _wheres = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(3, Name=@"wheres", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> wheres
    {
      get { return _wheres; }
    }
  
    private int _pageNo;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"pageNo", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pageNo
    {
      get { return _pageNo; }
      set { _pageNo = value; }
    }
    private int _pageSize;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"pageSize", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pageSize
    {
      get { return _pageSize; }
      set { _pageSize = value; }
    }
    private string _resultFmart = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"resultFmart", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string resultFmart
    {
      get { return _resultFmart; }
      set { _resultFmart = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"QueryResultPt")]
  public partial class QueryResultPt : global::ProtoBuf.IExtensible
  {
    public QueryResultPt() {}
    
    private string _token;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string token
    {
      get { return _token; }
      set { _token = value; }
    }
    private int _count;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int count
    {
      get { return _count; }
      set { _count = value; }
    }
    private string _result;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string result
    {
      get { return _result; }
      set { _result = value; }
    }
    private int _success = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"success", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int success
    {
      get { return _success; }
      set { _success = value; }
    }
    private string _msg = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string msg
    {
      get { return _msg; }
      set { _msg = value; }
    }
    private string _resultFmart = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"resultFmart", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string resultFmart
    {
      get { return _resultFmart; }
      set { _resultFmart = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ExecutePt")]
  public partial class ExecutePt : global::ProtoBuf.IExtensible
  {
    public ExecutePt() {}
    
    private string _token;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string token
    {
      get { return _token; }
      set { _token = value; }
    }
    private string _sql;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"sql", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sql
    {
      get { return _sql; }
      set { _sql = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _wheres = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(3, Name=@"wheres", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> wheres
    {
      get { return _wheres; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ExecuteResultPt")]
  public partial class ExecuteResultPt : global::ProtoBuf.IExtensible
  {
    public ExecuteResultPt() {}
    
    private string _token;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string token
    {
      get { return _token; }
      set { _token = value; }
    }
    private int _success;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"success", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int success
    {
      get { return _success; }
      set { _success = value; }
    }
    private string _msg = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string msg
    {
      get { return _msg; }
      set { _msg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}