//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: MessagePt.proto
namespace ChivaVR.Net.Packet
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessagePt")]
  public partial class MessagePt : global::ProtoBuf.IExtensible
  {
    public MessagePt() {}
    
    private string _msgtype;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"msgtype", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string msgtype
    {
      get { return _msgtype; }
      set { _msgtype = value; }
    }
    private string _msg;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string msg
    {
      get { return _msg; }
      set { _msg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}