//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ResourcePt.proto
namespace ChivaVR.Net.Packet
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResourcePt")]
  public partial class ResourcePt : global::ProtoBuf.IExtensible
  {
    public ResourcePt() {}
    
    private int _service;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"service", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int service
    {
      get { return _service; }
      set { _service = value; }
    }
    private string _objectid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"objectid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string objectid
    {
      get { return _objectid; }
      set { _objectid = value; }
    }
    private string _pathfile;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"pathfile", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string pathfile
    {
      get { return _pathfile; }
      set { _pathfile = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _folder;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"folder", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int folder
    {
      get { return _folder; }
      set { _folder = value; }
    }
    private int _version = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int version
    {
      get { return _version; }
      set { _version = value; }
    }
    private string _lastwrite;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"lastwrite", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string lastwrite
    {
      get { return _lastwrite; }
      set { _lastwrite = value; }
    }
    private string _remark;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"remark", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string remark
    {
      get { return _remark; }
      set { _remark = value; }
    }
    private string _crc;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"crc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string crc
    {
      get { return _crc; }
      set { _crc = value; }
    }
    private string _msg;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string msg
    {
      get { return _msg; }
      set { _msg = value; }
    }
    private int _success = default(int);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"success", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int success
    {
      get { return _success; }
      set { _success = value; }
    }
    private string _versionname = "";
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"versionname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string versionname
    {
      get { return _versionname; }
      set { _versionname = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResourceQueryPt")]
  public partial class ResourceQueryPt : global::ProtoBuf.IExtensible
  {
    public ResourceQueryPt() {}
    
    private string _objectid = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"objectid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string objectid
    {
      get { return _objectid; }
      set { _objectid = value; }
    }
    private string _pathfile = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"pathfile", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string pathfile
    {
      get { return _pathfile; }
      set { _pathfile = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _folder = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"folder", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int folder
    {
      get { return _folder; }
      set { _folder = value; }
    }
    private int _version = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int version
    {
      get { return _version; }
      set { _version = value; }
    }
    private string _lastwrite = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"lastwrite", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string lastwrite
    {
      get { return _lastwrite; }
      set { _lastwrite = value; }
    }
    private string _remark = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"remark", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string remark
    {
      get { return _remark; }
      set { _remark = value; }
    }
    private string _crc = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"crc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string crc
    {
      get { return _crc; }
      set { _crc = value; }
    }
    private string _versionname = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"versionname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string versionname
    {
      get { return _versionname; }
      set { _versionname = value; }
    }
    private int _pageSize;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"pageSize", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pageSize
    {
      get { return _pageSize; }
      set { _pageSize = value; }
    }
    private int _pageNo;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"pageNo", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pageNo
    {
      get { return _pageNo; }
      set { _pageNo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResourceResultPt")]
  public partial class ResourceResultPt : global::ProtoBuf.IExtensible
  {
    public ResourceResultPt() {}
    
    private int _count;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int count
    {
      get { return _count; }
      set { _count = value; }
    }
    private int _pageNo;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"pageNo", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pageNo
    {
      get { return _pageNo; }
      set { _pageNo = value; }
    }
    private readonly global::System.Collections.Generic.List<ChivaVR.Net.Packet.ResourcePt> _resourceList = new global::System.Collections.Generic.List<ChivaVR.Net.Packet.ResourcePt>();
    [global::ProtoBuf.ProtoMember(3, Name=@"resourceList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ChivaVR.Net.Packet.ResourcePt> resourceList
    {
      get { return _resourceList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}