//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: TemplatePt.proto
namespace ChivaVR.Net.Packet
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TemplateEnterPt")]
  public partial class TemplateEnterPt : global::ProtoBuf.IExtensible
  {
    public TemplateEnterPt() {}
    
    private string _fieldOne;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"fieldOne", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string fieldOne
    {
      get { return _fieldOne; }
      set { _fieldOne = value; }
    }
    private string _fieldTwo;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"fieldTwo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string fieldTwo
    {
      get { return _fieldTwo; }
      set { _fieldTwo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TemplateEnterInfoPt")]
  public partial class TemplateEnterInfoPt : global::ProtoBuf.IExtensible
  {
    public TemplateEnterInfoPt() {}
    
    private string _fieldInfoOne;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"fieldInfoOne", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string fieldInfoOne
    {
      get { return _fieldInfoOne; }
      set { _fieldInfoOne = value; }
    }
    private string _fieldInfoTwo;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"fieldInfoTwo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string fieldInfoTwo
    {
      get { return _fieldInfoTwo; }
      set { _fieldInfoTwo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}